name: Bug report
description: Report a bug to help us improve Gannet.
title: "[BUG] <Summarize the bug here>"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Please first search to see if an open or closed issue already exists for the bug you encountered before submitting this issue.
        
  - type: input
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Copy-paste the command syntax or script that generated the bug.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: Include screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Gannet version
      description: Which version of Gannet are you running?
      placeholder: ex. 3.2.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: MATLAB version
      description: Which version of MATLAB are you running?
      placeholder: ex. R2022b
    validations:
      required: true

  - type: textarea
    attributes:
      label: Operating system
      description: Which operating system are you running and which version is it?
      placeholder: ex. macOS Ventura 13.2.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context about the problem, if relevant.
    validations:
      required: false
