name: Automerge update_dependencies pull requests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

run-name: ${{ github.event_name }} - ${{ github.actor }} automerge update_dependencies PR

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  check_suite:
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request_target' &&
        !github.event.pull_request.draft &&
        (github.event.pull_request.user.login == 'github-actions[bot]' ||
        github.event.pull_request.user.login == 'markmikkelsen') &&
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.head.ref == 'bot/update-dependencies'
      ) || (
        github.event_name == 'check_suite' &&
        github.event.check_suite.conclusion == 'success' &&
        github.event.check_suite.head_branch == 'bot/update-dependencies'
      )

    steps:
      - name: Merge pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
