name: Update bids-matlab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: ${{ github.actor }} is updating bids-matlab

on:
  schedule:
  - cron: 0 0 * * 1 # Every monday
  workflow_dispatch:

jobs:
  update-bids-matlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gannet repo
        uses: actions/checkout@v5

      - name: Checkout bids-matlab repo
        uses: actions/checkout@v5
        with:
          repository: bids-standard/bids-matlab
          path: bids-matlab_tmp/

      - name: Copy files from separate repo to current repo
        run: |
          rsync -av --exclude '.git' bids-matlab_tmp/ bids-matlab/
          rm -rf bids-matlab_tmp/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Sync with bids-standard/bids-matlab repo
          assignees: markmikkelsen
          base: main
          delete-branch: true
          title: '[BOT] Update bids-matlab'
          body: Done by a [GitHub Action](https://github.com/markmikkelsen/Gannet/blob/main/.github/workflows/update_bids-matlab.yml)
